source 'https://rubygems.org'

gem 'rake'
# Add your dependencies here:
gem 'bubble-wrap'
gem 'afmotion'

# gem "teacup"
# gem "sugarcube"
# gem "sweettea"
# gem 'bubble-wrap'
# gem "motion-awesome" # now handled by sugarcube-awesome
# gem "motion-map"
# gem "geomotion"
# #gem "motion-xray"
# gem "motion-rubberstamp"#, :git => "git@github.com:IconoclastLabs/motion-rubberstamp.git"
# gem "awesome_print_motion"
